# Generated by Django 5.1.6 on 2025-02-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="map_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
