# Generated by Django 5.1.6 on 2025-02-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_location', to='locations.location')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_location', to='posts.post')),
            ],
        ),
    ]
