name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env  # GitHub Secrets에서 가져와서 .env 파일 생성

      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Start Containers
        run: docker compose up --build -d
