name: Deploy

on:
  push:
    branches:
      - develop  # develop 브랜치에 push될 때 실행
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # 최신 버전
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/myapp:latest .
          docker push ${{ secrets.DOCKERHUB_NAME }}/myapp:latest
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/myapp-nginx:latest ./nginx
          docker push ${{ secrets.DOCKERHUB_NAME }}/myapp-nginx:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker network create myapp_network
            docker volume create static-volume
            docker pull ${{ secrets.DOCKERHUB_NAME }}/myapp:latest
            docker stop ${{ secrets.DJANGO_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DJANGO_CONTAINER_NAME }} || true
            docker run -d --network myapp_network --name ${{ secrets.DJANGO_CONTAINER_NAME }} -p 8000:8000 -v static-volume:/app/static --env-file ~/backend_3rd/.env ${{ secrets.DOCKERHUB_NAME }}/myapp:latest
            docker pull ${{ secrets.DOCKERHUB_NAME }}/myapp-nginx:latest
            docker stop ${{ secrets.NGINX_CONTAINER_NAME }} || true
            docker rm ${{ secrets.NGINX_CONTAINER_NAME }} || true
            docker run -d --network myapp_network --name ${{ secrets.NGINX_CONTAINER_NAME }} -p 80:80 -v static-volume:/app/static ${{ secrets.DOCKERHUB_NAME }}/myapp-nginx:latest