name: Deploy

on:
  push:
    branches:
      - develop  # develop 브랜치에 push될 때 실행
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # 최신 버전
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/app:latest .
          docker push ${{ secrets.DOCKERHUB_NAME }}/app:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
#            echo "DB_HOST=database.example.com" > .env  # 환경 변수
            docker pull ${{ secrets.DOCKERHUB_NAME }}/app:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 8000:8000 --env-file .env ${{ secrets.DOCKERHUB_NAME }}/app:latest
